### ISSUE TITLE
Wildcards in URL?

### ISSUE THREAD

**Issue by mackoftrack** [akamai/cli-purge#19]
Are wildcards in the URL supported?

**Comment by javiergarza** [comment]
@mackoftrack No, sorry but the purge CLI does not support wildcards because the [underlaying API](https://developer.akamai.com/api/core_features/fast_purge/v3.html) endpoint doesn't support wildcards. 

You can however use [cache-tags](https://developer.akamai.com/api/core_features/fast_purge/v3.html#concepts) to be able to purge in a way that makes the most sense to you, like purging all products in a given category
